### ISSUE TITLE
[Java] file layout: pad numbers in filenames

### ISSUE THREAD

**Issue by vlkl-sap** [testable-eu/sast-testability-patterns#14]
## Problem statement
Directories are currently sorted like this by default:
```
69_pass_variable_between_java_files
6_callable
70_raw_types
```

## Proposed changes

While it is possible to use `ls -v`, consider pading all numbers, i.e., `6` to `006`, etc.

**Comment by compaluca** [comment]
Also this is a good point, similar to #15. Merging them together in #15.
