### ISSUE TITLE
Update TP: Java: 88_stream

### ISSUE THREAD

**Issue by vlkl-sap** [testable-eu/sast-testability-patterns#16]
## Testability pattern

88_stream

## Problem statement

The instance directory `88_stream/1_instance_88_stream` does not follow the layout convention and contains two further subinstance (?) directories. Furthermore, these directories lack the necessary libraries.

## Proposed changes

Rearrange the files/instances/patterns to follow the convention. Add the `lib` directories.

**Comment by compaluca** [comment]
indeed there were several mistakes in that pattern. The two further sub-instances were redundant wrt the other two instances. This should be solved now
