### ISSUE TITLE
PHP: Pattern 19 Instance 2 CPG generation fails

### ISSUE THREAD

**Issue by felix-20** [testable-eu/sast-testability-patterns#42]
## Problem statement
For [Pattern 19 Instance 2](https://github.com/testable-eu/sast-testability-patterns/tree/master/PHP/19_closures/2_instance_19_closures) the cpg generation fails.

This seems to be a known issue in the php-cpg generator (https://github.com/testable-eu/sast-testability-patterns/issues/9#issuecomment-1424144053).

@mal-tee are there any updates on this?

**Comment by mal-tee** [comment]
Yes, I fixed that upstream. Should I bump the docker image?

**Comment by mal-tee** [comment]
Done. https://hub.docker.com/r/malt33/php-cpg
